export default {
  HAVEYOUEVERTHOUGHTOFEMIGRATING: {
    cleanTitle: 'HAVEYOUEVERTHOUGHTOFEMIGRATING',
    frames: 720,
    previousVideoTokenEndingPoint: 0,
    sortOrder: 1,
    subtitle: 'Liquid Poster No.1',
    title: 'HAVEYOUEVERTHOUGHTOFEMIGRATING?',
  },
  IMAGINEYOURSELFWITHOUTAHOME: {
    cleanTitle: 'IMAGINEYOURSELFWITHOUTAHOME',
    frames: 1080,
    previousVideoTokenEndingPoint: 720,
    sortOrder: 2,
    subtitle: 'Liquid Poster No.2',
    title: 'IMAGINEYOURSELFWITHOUTAHOME',
  },
  HAVEYOUEVERSTOLENANIDEA: {
    cleanTitle: 'HAVEYOUEVERSTOLENANIDEA',
    frames: 540,
    previousVideoTokenEndingPoint: 1800,
    sortOrder: 3,
    subtitle: 'Liquid Poster No.3',
    title: 'HAVEYOUEVERSTOLENANIDEA?',
  },
  AREYOUAFRAIDOFTHEPOOR: {
    cleanTitle: 'AREYOUAFRAIDOFTHEPOOR',
    frames: 720,
    previousVideoTokenEndingPoint: 2340,
    sortOrder: 4,
    subtitle: 'Liquid Poster No.4',
    title: 'AREYOUAFRAIDOFTHEPOOR?',
  },
  ANYTHINGTHATINDICATESYOUHAVEASENSEOFHUMOR: {
    cleanTitle: 'ANYTHINGTHATINDICATESYOUHAVEASENSEOFHUMOR',
    frames: 720,
    previousVideoTokenEndingPoint: 3060,
    sortOrder: 5,
    subtitle: 'Liquid Poster No.5',
    title: 'ANYTHINGTHATINDICATESYOUHAVEASENSEOFHUMOR',
  },
};
