export default {
  HAVEYOUEVERTHOUGHTOFEMIGRATING: {
    cleanTitle: 'HAVEYOUEVERTHOUGHTOFEMIGRATING',
    frames: 720,
    previousVideoTokenEndingPoint: 0,
    sortOrder: 1,
    subtitle: 'Liquid poster No.1',
    title: 'HAVEYOUEVERTHOUGHTOFEMIGRATING?',
  },
  IMAGINEYOURSELFWITHOUTAHOME: {
    cleanTitle: 'IMAGINEYOURSELFWITHOUTAHOME',
    frames: 1080,
    previousVideoTokenEndingPoint: 12,
    sortOrder: 2,
    subtitle: 'Liquid poster No.2',
    title: 'IMAGINEYOURSELFWITHOUTAHOME',
  },
  HAVEYOUEVERSTOLENANIDEA: {
    cleanTitle: 'HAVEYOUEVERSTOLENANIDEA',
    frames: 540,
    previousVideoTokenEndingPoint: 30,
    sortOrder: 3,
    subtitle: 'Liquid poster No.3',
    title: 'HAVEYOUEVERSTOLENANIDEA?',
  },
  AREYOUAFRAIDOFTHEPOOR: {
    cleanTitle: 'AREYOUAFRAIDOFTHEPOOR',
    frames: 720,
    previousVideoTokenEndingPoint: 49,
    sortOrder: 4,
    subtitle: 'Liquid poster No.4',
    title: 'AREYOUAFRAIDOFTHEPOOR?',
  },
  ANYTHINGTHATINDICATESYOUHAVEASENSEOFHUMOR: {
    cleanTitle: 'ANYTHINGTHATINDICATESYOUHAVEASENSEOFHUMOR',
    frames: 720,
    previousVideoTokenEndingPoint: 51,
    sortOrder: 5,
    subtitle: 'Liquid poster No.5',
    title: 'ANYTHINGTHATINDICATESYOUHAVEASENSEOFHUMOR',
  },
};
